Parameters:
  Environment:
    Description: Deployment environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prd
    ConstraintDescription: Must be either dev or prd.

Conditions:
  IsProduction: !Equals [!Ref Environment, 'prd']

Resources:
  ChaiChatDemoFrontendSite: # update this
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'chai-chat-demo-frontend-site-${Environment}' # update this
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  ChaiChatDemoFrontendSitePolicy: # update this
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref ChaiChatDemoFrontendSite # update this
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${ChaiChatDemoFrontendSite}/*' # update this

  ChaiChatDemoCloudFront: # update this
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub 'chai-chat-demo.foobar.dev'
        Origins:
          - DomainName: !Sub '${ChaiChatDemoFrontendSite}.s3-website-${AWS::Region}.amazonaws.com' # update this
            Id: ReactApp
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        Comment: !Sub 'chai-chat-demo (${Environment})' # update this
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: ReactApp
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:868085652288:certificate/3dcb9b40-349b-4e0d-9368-1c6dd8fa610d # cert covers *.foobar.dev
          SslSupportMethod: 'sni-only'
  MyDNSRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: Z00331582MFBUMN4BZ0YE # This if for foobar.dev
      Name: !Sub 'chai-chat-demo.foobar.dev'
      Type: 'A'
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # This is CloudFront's hosted zone ID, don't change
        DNSName: !GetAtt [ChaiChatDemoCloudFront, DomainName] # update this